# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dad23304e04694529314829131c87b082ed32b6c302ab64366744e4e8cfc35ce4d4e094f9042cf85a15eec924577685cea5a65c55f94c19df4828a41de7b6f5

test:
  secret_key_base: 55e3c9cc20a189b7d6835f946036020245bf12c5890d3ac7185521eb70a18eb4a28dffcb36c98903b4433edd274babdce60fb1067f02db45197ba6cd27de51c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
